version: '3.7'
services:
    marathon-api:
        build: ..
        command: sh -c './scripts/wait-for.sh postgres:${DB_PORT} -- python -m src.app'
        container_name: marathon-api
        depends_on:
            - postgres
        env_file:
            - ../.env
        image: marathon-api
        ports:
            - 5000:5000
        restart: always
    postgres:
        build:
            context: .
            dockerfile: postgres.Dockerfile
        container_name: ${DB_HOST}
        environment:
            - POSTGRES_MULTIPLE_DATABASES=${DB_TEST_NAME}
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
        image: marathon-api-postgres
        ports:
            - ${DB_PORT}:5432
