version: '3.7'
services:
    marathon-api:
        build: ..
        command: sh -c './scripts/wait-for.sh postgres:5432 -- python -m src.app'
        container_name: marathon-api
        depends_on:
            - postgres
        env_file:
            - ../.env
        image: marathon-api
        ports:
            - 5000:5000
        restart: always
        volumes:
            - type: bind
              source: ../
              target: /app
    swagger-ui:
        container_name: swagger-ui
        environment:
            - SWAGGER_JSON=/swagger.yml
        image: swaggerapi/swagger-ui
        ports:
            - 8080:8080
        volumes:
            - ../swagger.yml:/swagger.yml
    postgres:
        build:
            context: .
            dockerfile: postgres.Dockerfile
        container_name: postgres
        environment:
            - POSTGRES_MULTIPLE_DATABASES=marathon_test
            - POSTGRES_PASSWORD=password
        image: marathon-api-postgres
        ports:
            - 5432:5432
