version: '3.7'
services:
    marathon-api:
        build: ..
        container_name: marathon-api
        env_file:
            - ../.env
        image: marathon-api
        ports:
            - 5000:5000
        restart: always
    postgres:
        build:
            context: .
            dockerfile: postgres.Dockerfile
        container_name: postgres
        environment:
            - POSTGRES_MULTIPLE_DATABASES=marathon_test
            - POSTGRES_PASSWORD=password
        image: marathon-api-postgres
        ports:
            - 5432:5432
