version: '3.7'
services:
    marathon-api:
        build: .
        container_name: marathon-api
        env_file:
            - ../env/dev.env
        ports:
            - 5000:5000
        restart: always
        volumes:
            - type: bind
              source: ../
              target: /app
    swagger-ui:
        container_name: swagger-ui
        environment:
            - SWAGGER_JSON=/swagger.yml
        image: swaggerapi/swagger-ui
        ports:
            - 8080:8080
        volumes:
            - ../swagger.yml:/swagger.yml
    postgres:
        container_name: postgres
        environment:
            - POSTGRES_MULTIPLE_DATABASES=marathon_test
            - POSTGRES_PASSWORD=password
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - ../initdb.d:/docker-entrypoint-initdb.d
